BLIP commit has been deleted？
RuntimeError: Couldn't checkout commit 48211a1594f1321b00f14c9f7a5b4813144b2fb9 for BLIP.
Command: "git" -C "repositories/BLIP" checkout 48211a1594f1321b00f14c9f7a5b4813144b2fb9
Error code: 128

Seems like BLIP commit has been deleted？ 
The only commit I can find is https://github.com/salesforce/BLIP/commit/3a29b7410476bf5f2ba0955827390eb6ea1f4f9d
Can change this commit hash solve the problem？